<?=$menu?>
<div id="page-wrapper">
	<h1 class="page-header margin-top-none">Visitor Analytics</small></h1>
	<p class="lead">Location, IP address and time stamp of each visitor to each tracked page</p>
	<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>Email</th>
				<th>Date</th>
				<th>IP</th>
				<th>City</th>
				<th>State</th>
				<th>Source</th>
				<th>Referrer</th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<th>Email</th>
				<th>Date</th>
				<th>IP</th>
				<th>City</th>
				<th>State</th>
				<th>Source</th>
				<th>Referrer</th>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<td>guy@cisco.com</td>
				<td>10/02/15</td>
				<td>127.0.0.1</td>
				<td>Baltimore</td>
				<td>Maryland</td>
				<td>ezproposal</td>
				<td>ezproposal</td>
			<tr>
				<td>girl@cisco.com</td>
				<td>10/03/15</td>
				<td>127.0.0.1</td>
				<td>Baltimore</td>
				<td>Maryland</td>
				<td>captain-uccaas</td>
				<td>captain-uccaas</td>
			</tr>
		</tbody>
	</table>
</div>
<?=$footer?>